version: '1'
services:
  cqrs-kafka12:
    container_name: cqrs-kafka12
    build:
      context: .
      dockerfile: Dockerfile
    image: cqrs-kafka12:latest
    ports:
      - 8080:8080
    networks:
      - cqrs-kafka12-network
networks:
  cqrs-kafka12-network:
    driver: bridge