version: '1'
services:
  cqrs-kafka19:
    container_name: cqrs-kafka19
    build:
      context: .
      dockerfile: Dockerfile
    image: cqrs-kafka19:latest
    ports:
      - 8080:8080
    networks:
      - cqrs-kafka19-network
networks:
  cqrs-kafka19-network:
    driver: bridge