version: '1'
services:
  cqrs-kafka7:
    container_name: cqrs-kafka7
    build:
      context: .
      dockerfile: Dockerfile
    image: cqrs-kafka7:latest
    ports:
      - 8080:8080
    networks:
      - cqrs-kafka7-network
networks:
  cqrs-kafka7-network:
    driver: bridge