version: '1'
services:
  cqrs-kafka14:
    container_name: cqrs-kafka14
    build:
      context: .
      dockerfile: Dockerfile
    image: cqrs-kafka14:latest
    ports:
      - 8080:8080
    networks:
      - cqrs-kafka14-network
networks:
  cqrs-kafka14-network:
    driver: bridge