version: '1'
services:
  cqrs-kafka20:
    container_name: cqrs-kafka20
    build:
      context: .
      dockerfile: Dockerfile
    image: cqrs-kafka20:latest
    ports:
      - 8080:8080
    networks:
      - cqrs-kafka20-network
networks:
  cqrs-kafka20-network:
    driver: bridge